/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CausalRouteImport } from './routes/causal'
import { Route as IndexRouteImport } from './routes/index'

const CausalRoute = CausalRouteImport.update({
  id: '/causal',
  path: '/causal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/causal': typeof CausalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/causal': typeof CausalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/causal': typeof CausalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/causal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/causal'
  id: '__root__' | '/' | '/causal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CausalRoute: typeof CausalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/causal': {
      id: '/causal'
      path: '/causal'
      fullPath: '/causal'
      preLoaderRoute: typeof CausalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CausalRoute: CausalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
